[program:android-avd]
command=/app/entrypoint.sh
user=root
environment=DISPLAY=":1.0",HOME="/root"
priority=30
startsecs=30
startretries=3
autorestart=unexpected
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
